import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import axiosRequest from '../utils/axiosRequest'
import BasicLayout from '../layouts/BasicLayout'
import Container from '@material-ui/core/Container'
import { useSchoolsContext, SchoolType } from '../src/store'

export async function getStaticProps() {

  let schoolsData:SchoolType[] = []

  const resposne = await axiosRequest().get("/", {
    params: {
      "school.state": "Tx",
      "per_page": 1,
      _fields: "school.name,school.degrees_awarded,school.faculty_salary,latest.admissions.admission_rate,shcool.size"
    }
  })
  
  schoolsData = resposne.data.results

  return {
    props: {
      schoolsData
    }, // will be passed to the page component as props
  }
}


export default function Home({ schoolsData }:{ schoolsData:SchoolType[] }) {
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  const { load, schools } = useSchoolsContext()

  load(schoolsData)

  return (
    <BasicLayout>
      <Container className="page-container">
        <pre>{JSON.stringify({schools}, null, 4)}</pre>
      </Container>
    </BasicLayout>
  )
}
